language: java

jdk:
  - oraclejdk8

sudo:
  - required

install: true

script:
  - mvn clean install

after_success:
  - ./deploy.sh

notifications:
  email:
  - herve.tchepannou@gmail.com

deploy:
  - provider: s3
    access_key_id: "$AWS_ACCESS_KEY"
    secret_access_key: "$AWS_SECRET_KEY"
    bucket: "io.tchepannou.kribi"
    skip_cleanup: true
    upload-dir: repository/kribi/$TRAVIS_COMMIT
    local_dir: target/deploy
    on:
      branch: master

after_deploy:
  - wget http://kribi.tchepannou.io/v1/application/kribi/init_artifact?version=$TRAVIS_COMMIT
