language: java

jdk:
  - oraclejdk8

sudo:
  - required

install: true

script:
  - mvn clean install

after_success:
  - curl -X POST -d @target/kribi.jar -H "api_key: $KRIBI_API_KEY" http://kribi.tchepannou.io/artifact/kribi/$TRAVIS_PULL_REQUEST_SHA

notifications:
  email:
  - herve.tchepannou@gmail.com
