kribi:
  namespace: "io.tchepannou"
  aws:
    bucket: "${kribi.namespace}.kribi"

spring:
  http:
    multipart:
      max-file-size: 200000000  # 200Mb
      max-request-size: 200000000  # 200Mb

swagger:
  version: "1.0"
  title: Kribi
  description: "Kribi deploys your application to the cloud"
  termsPath: ""
  email: "herve.tchepannou@gmail.com"
  licenceType: ""
  licencePath: "#"

endpoints:
  enabled: true
  health:
    sensitive: false
  info:
    sensitive: false
  metrics:
    sensitive: false

logging:
  level:
    root: INFO
    io.tchepannou.kribi: INFO
    com.amazonaws: WARN
    com.jcabi: WARN
    org: WARN
    io: WARN
    springfix: WARN

  pattern:
    console: "%d Type=%level TransactionId=%X{TransactionId} Message='%m'%n"
    file: "%d Type=%level TransactionId=%X{TransactionId} Message='%m'%n"
